### ISSUE TITLE
Reference links to documentation are broken

### ISSUE THREAD

**Issue by cathyxz** [googlecodelabs/workbox-lab#14]
The [codelab](https://codelabs.developers.google.com/codelabs/workbox-lab/) contains multiple links to the service worker library documentation (e.g. https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-sw.WorkboxSW#main). Many of the links are broken. Sorry to file here, but this is where "file a bug" on the codelab directs, and I don't know where the actual text / content of the codelab is located for updating.

**Comment by nasearle** [comment]
Hi Cathy, thanks for bringing this up! These links are broken because the Workbox v3 documentation was just published. We'll publish a new version of the codelab in the next couple days.

**Comment by cathyxz** [comment]
+1
