### ISSUE TITLE
10. Optional: Add a customized cacheFirst cache strategy

### ISSUE THREAD

**Issue by johndavemanuel** [googlecodelabs/workbox-lab#25]
I try the challenge on the Step 10 by copying and modifying the "Article" code for the Post pages and it seems that it cannot work like that. I check the solution and found out the little differences like

1. There is a "page\" on the registerRoute.
2. workbox.routing.registerRoute is using catch

Can anyone explain to me why the article code cannot work with post pages? Considering that I change the required changes?

**Comment by DavidScales** [comment]
Sorry for the slow reply! The challenge sections are open ended so if your code is not working and it's different from the solution, it would be helpful to see what you're doing. If you're still working on this issue, could you post your code?

**Comment by johndavemanuel** [comment]
Hi!

Thanks for replying.
Let me check my code.

**Comment by DavidScales** [comment]
Closing this for now, feel free to re-open if you want to review the code
