### ISSUE TITLE
npm install --global workbox-cli@^3.0.0

### ISSUE THREAD

**Issue by w-nema** [googlecodelabs/workbox-lab#31]
The lab says "npm install --global workbox-cli@^3.0.0", which freezes the command line on Windows after the first prompt. What worked instead is just "npm install --global workbox-cli"

**Comment by DavidScales** [comment]
I think there may be an issue on Windows for Workbox v3. If using the current version (v5) works, that's great 👍  

I'm not able to update the lab instructions right now with the Workbox v5 API but it looks pretty similar to v3, so hopefully the lab is still valuable
